Add start low power periodic measurement
adafruit/Adafruit_CircuitPython_SCD4X pull request #6
Opened 2021-08-20 07:32 UTC by enosh

Saw this command in the data sheet and wanted to use it.
The function name is `start_low_periodic_measurement` instead of `start_low_power_periodic_measurement` to fit the length pylint wants.

Tested with a Feather RP2040 and the new SCD40 STEMMA QT breakout. Around 30 seconds between measurements.
![Screen Shot 2021-08-19 at 23 06 48](https://user-images.githubusercontent.com/3087025/130192260-ae0567d2-7633-40af-bb29-ab59c7cc72b5.png)

First time submitter! Hope I'm not missing anything.

2021-08-20 16:02 UTC, kattni commented
@enosh Thanks for your contribution! I am working with this sensor and will test it either today or Tuesday. Running CI now, which will verify syntax and formatting, etc.

2021-08-20 16:03 UTC, ladyada approved these changes

2021-08-20 16:04 UTC, ladyada commented
didnt test but lgtm

2021-08-24 15:39 UTC, CrakeNotSnowman reviewed
I double checked the datasheet just to verify the `_SCD4X_STARTLOWPOWERPERIODICMEASUREMENT` hex of `0x21AC` is correct. But in the datasheet it says there's no delay needed after the command is sent.

Is there a reason you added a delay of 0.01s?

2021-08-24 16:14 UTC, enosh commented
I used `start_periodic_measurement` for reference which also has no delay specified in the datasheet. Just tested both without a delay and it doesn't seem to make a difference. But I assume a delay wouldn't hurt, right?

2021-08-24 17:13 UTC, CrakeNotSnowman requested changes
If that's the reasoning, then I'd err on the side of following the datasheet, and not having a delay. My main motivation is because I usually use datasheets as my mental 'square one' so if I have a bug I can't easily solve, I go back to that to make sure I can follow along with the code. 

While you're right, a delay doesn't hurt unless you're doing really time sensitive stuff, the sensor reads have a built in delay with `if scd4x.data_ready`, so I think it is safe to remove this delay in favor of keeping with the sensor's datasheet.

Outside of that, awesome PR! Thank you!

2021-08-24 17:15 UTC, kattni requested changes
Thanks again, @enosh. I agree with @CrakeNotSnowman on the delay. Please remove it, and if there are issues in the future, we have this discussion to fall back on.

2021-08-24 20:08 UTC, CrakeNotSnowman approved these changes
That matches the datasheet as far as I'm able to tell.

Thank you for making these additional changes! I really appreciate it!

2021-08-24 20:11 UTC, kattni approved these changes
Thanks so much for adding this. @enosh!

2021-08-24 20:14 UTC, merged